feat: new profile type parser
Tinkoff/gatling-picatinny pull request #120
Opened 2022-09-07 09:42 UTC by daylikon

`val scn = ProfileBuilderNew.buildFromYaml(profileConfigName).selectProfile("maxPerf").toRandomScenario`

2022-09-08 08:46 UTC, 3alster commented on src/main/scala/ru/tinkoff/gatling/profile/ProfileBuilderNew.scala
> +    val requestParsedHeaders: Map[String, String] = requestHeaders.map { case regexHeader(a, b) => (a, b) }.toMap
тут спокойно могут быть пробелы в значениях хэдера, типа
```          
headers:
     - 'greeting: Hello world!'
 ```

2022-09-08 09:18 UTC, 3alster commented on src/main/scala/ru/tinkoff/gatling/profile/ProfileBuilderNew.scala
> +      .getOrElse(throw new NoSuchElementException("No path in params"))
здесь наверное правильнее будет использовать пустой путь, чтобы обращения шли на baseUrl

```suggestion
      .getOrElse("")
```

2022-09-08 09:46 UTC, 3alster commented on src/main/scala/ru/tinkoff/gatling/profile/ProfileBuilderNew.scala
> +    requestMethod match {
здесь думаю проще заюзать `http(requestName).httpRequest(requestMethod, uri)` и тогда будет унифицирована обработка, ведь метод может быть любой, также как и боди может быть всегда

2022-09-25 18:30 UTC, jigarkhwar requested changes

2022-09-25 18:30 UTC, jigarkhwar commented on src/test/scala/ru/tinkoff/gatling/profile/ProfileBuilderTest.scala
> +    Some("link.ru/v1alpha1"),
Почему обязательные поля в ямле являются опшенами?
Нужно валидировать json/yaml по json schema как то наверное разве нет?

2022-09-25 18:36 UTC, jigarkhwar commented on src/main/scala/ru/tinkoff/gatling/profile/ProfileBuilderNew.scala
> +      requests.foldLeft(List.empty[(Double, ChainBuilder)]) { case (sum, (intensity, chain)) =>
посмотри на функции списка sum или reduce
`myList.map(_.price).sum`
or
`myList.reduce(_ + _)`

2022-09-26 12:24 UTC, daylikon commented on src/test/scala/ru/tinkoff/gatling/profile/ProfileBuilderTest.scala
> +    Some("link.ru/v1alpha1"),
сделал их не опшенами, теперь он будет выкидывать при парсинге ямла с указанием, какое поле он не нашёл.

2022-09-28 18:29 UTC, jigarkhwar commented on src/main/scala/ru/tinkoff/gatling/profile/ProfileBuilderNew.scala
> +case class Yaml(apiVersion: Option[String], kind: Option[String], metadata: Option[Metadata], spec: List[OneProfile]) {
apiVersion: Option[String], kind: Option[String], metadata: Option[Metadata]

а это почему Option? Разве оно может отсутствовать?

2022-09-28 18:36 UTC, jigarkhwar requested changes

2022-09-28 18:36 UTC, jigarkhwar commented on src/main/scala/ru/tinkoff/gatling/profile/ProfileBuilderNew.scala
> +    val profileList: List[OneProfile] = spec.filter(_.name == profileName)
есть ещё метод find, кажется тебе он нужен

2022-09-28 18:36 UTC, jigarkhwar commented on src/test/scala/ru/tinkoff/gatling/profile/ProfileBuilderTest.scala
> +    Some("link.ru/v1alpha1"),
До сих пор опшен получается

2022-09-29 08:10 UTC, merged