feat: add ProfileBuilderNew for java
Tinkoff/gatling-picatinny pull request #138
Opened 2022-11-22 14:00 UTC by ddemonaz89

2022-11-23 11:21 UTC, red-bashmak commented on README.md
> +Kotlin example:
Perhaps this line should be higher up.

2022-11-23 11:28 UTC, ddemonaz89 commented on README.md
> +Kotlin example:
fix

2022-11-23 11:31 UTC, red-bashmak commented on README.md
>    Iterator<Map<String, Object>> vaultFeeder = VaultFeeder(vaultUrl, secretPath, roleId, secretId, keys);
New versions of Java allow this shorter form: `var vaultFeeder = ...`. More informartion [here](https://openjdk.org/jeps/286)

2022-11-23 11:44 UTC, red-bashmak commented on src/test/java/ru/tinkoff/gatling/javaapi/JavaProfileTest.java
> +            .buildFromYaml("perf/profiles.yml")
What will happen if here be a path to a file that doesn't exist?

2022-11-23 11:49 UTC, red-bashmak requested changes
Some fixes needed. More in comments

2022-11-29 06:15 UTC, jigarkhwar approved these changes

2022-11-29 06:17 UTC, merged